# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name u_index
#' @title Compute an index of community
#' @author P. Chevallier - April 2023
#' @param nz length of the concatenated time-series
#' @param yd initial vector of datetimes (in sec)
#' @details the function compute an index, which the number of apparition of the same datetime
#' in a time-series
#' @return vector of indexes
NULL

u_index <- function(nz, zd) {
    .Call(`_htsr_u_index`, nz, zd)
}

#' @name u_timestep
#' @title Compute values in a time-series with a fixed timestep
#' @author P. Chevallier - June 2023
#' @param te time end (in sec)
#' @param yd initial vector of datetimes (in sec)
#' @param yv initial vector of values
#' @param tst timestep (in mn)
#' @param iop operation index
#' @details iop = 1 for sum; 0 for mean; -2 for min and +2 for max
#' @return vector of values with fixed timestep
NULL

u_timestep <- function(te, yd, yv, tst, iop) {
    .Call(`_htsr_u_timestep`, te, yd, yv, tst, iop)
}

